### ISSUE TITLE
esdown vs babel

### ISSUE THREAD

**Issue by timoxley** [zenparsing/esdown#34]
Can you perhaps explain the difference between these two projects? i.e. why does esdown exist?

**Comment by zenparsing** [comment]
Sure.  This project was started a long time ago to support my need for:

- Writing code in ES6 before there was a babel (there was tracuer, though).
- Easily being able to experiment with the language.
- Creating and using my own tools, which I enjoy.

I still continue to use and refine esdown, but I won't likely add many features going forward.  Since ES6 support is taking off across the engines, I might create a "version 2" which takes ES6 as a starting point and adds support for ES7-ish things.

Babel is apparently meant to be a language processing platform, which esdown is certainly not.  Esdown is intended to be a fast and simple translation tool.
